Repository KiCad/kicad-packages3D, pull requests merged in 2019-01, with the labels that each got.

#498 MountingEquipment: moving DIN Rail adapter
  MountingEquipment.3dshapes/DINRailAdapter_3xM3_PhoenixContact_1201578.step
  MountingEquipment.3dshapes/DINRailAdapter_3xM3_PhoenixContact_1201578.wrl
Labels: Enhancement, Pending reviewer

#499 Fix orientation of TO-92Flat
  Package_TO_SOT_THT.3dshapes/TO-92Flat.step
  Package_TO_SOT_THT.3dshapes/TO-92Flat.wrl
Labels: Bug, Pending reviewer

#492 Transformers THT: Add model for Excelitas ZS1052 AC ignition coil
  Transformer_THT.3dshapes/Autotransformer_ZS1052-AC.step
  Transformer_THT.3dshapes/Autotransformer_ZS1052-AC.wrl
Labels: Pending footprint

#348 Added 3D models for Pulse PA4320
  Inductor_SMD.3dshapes/L_Pulse_PA4320.step
  Inductor_SMD.3dshapes/L_Pulse_PA4320.wrl
Labels: Addition, Pending reviewer, Re-push

#402 Adding SATA_Amphenol_10029364-001LF_Horizontal connector
  Connector_SATA_SAS.3dshapes/SATA_Amphenol_10029364-001LF_Horizontal.step
  Connector_SATA_SAS.3dshapes/SATA_Amphenol_10029364-001LF_Horizontal.wrl
Labels: Addition, Pending footprint, Pending reviewer

#387 Added Potentiometer_Bourns_3314J_Vertical
  Potentiometer_SMD.3dshapes/CREDITS.md
  Potentiometer_SMD.3dshapes/Potentiometer_Bourns_3314J_Vertical.step
  Potentiometer_SMD.3dshapes/Potentiometer_Bourns_3314J_Vertical.wrl
Labels: Addition, Pending reviewer

#411 Added Potentiometer_Bourns_3314G_Vertical
  Potentiometer_SMD.3dshapes/Potentiometer_Bourns_3314G_Vertical.step
  Potentiometer_SMD.3dshapes/Potentiometer_Bourns_3314G_Vertical.wrl
Labels: Addition, Pending reviewer, Re-push

#487 Added 3D model of Keystone 2993
  Battery.3dshapes/BatteryHolder_Keystone_2993.step
  Battery.3dshapes/BatteryHolder_Keystone_2993.wrl
Labels: Addition, Pending reviewer

#490 Added the non polarized bulk SMD capacitors
  Capacitor_SMD.3dshapes/C_Elec_10x10.2.step
  Capacitor_SMD.3dshapes/C_Elec_10x10.2.wrl
  Capacitor_SMD.3dshapes/C_Elec_3x5.4.step
  Capacitor_SMD.3dshapes/C_Elec_3x5.4.wrl
  Capacitor_SMD.3dshapes/C_Elec_4x5.4.step
  Capacitor_SMD.3dshapes/C_Elec_4x5.4.wrl
  Capacitor_SMD.3dshapes/C_Elec_4x5.8.step
  Capacitor_SMD.3dshapes/C_Elec_4x5.8.wrl
  Capacitor_SMD.3dshapes/C_Elec_5x5.4.step
  Capacitor_SMD.3dshapes/C_Elec_5x5.4.wrl
  Capacitor_SMD.3dshapes/C_Elec_5x5.8.step
  Capacitor_SMD.3dshapes/C_Elec_5x5.8.wrl
  Capacitor_SMD.3dshapes/C_Elec_6.3x5.4.step
  Capacitor_SMD.3dshapes/C_Elec_6.3x5.4.wrl
  Capacitor_SMD.3dshapes/C_Elec_6.3x5.8.step
  Capacitor_SMD.3dshapes/C_Elec_6.3x5.8.wrl
  Capacitor_SMD.3dshapes/C_Elec_6.3x7.7.step
  Capacitor_SMD.3dshapes/C_Elec_6.3x7.7.wrl
  Capacitor_SMD.3dshapes/C_Elec_8x10.2.step
  Capacitor_SMD.3dshapes/C_Elec_8x10.2.wrl
  Capacitor_SMD.3dshapes/C_Elec_8x5.4.step
  Capacitor_SMD.3dshapes/C_Elec_8x5.4.wrl
  Capacitor_SMD.3dshapes/C_Elec_8x6.2.step
  Capacitor_SMD.3dshapes/C_Elec_8x6.2.wrl
Labels: Addition, Pending reviewer

#491 Added 3D models of the capacitance trimmers
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZB4-A.step
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZB4-A.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZB4-B.step
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZB4-B.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZC3.step
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZC3.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZR1.step
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZR1.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZW4.step
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZW4.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZY2.step
  Capacitor_SMD.3dshapes/C_Trimmer_Murata_TZY2.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Sprague-Goodman_SGC3.step
  Capacitor_SMD.3dshapes/C_Trimmer_Sprague-Goodman_SGC3.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Voltronics_JN.step
  Capacitor_SMD.3dshapes/C_Trimmer_Voltronics_JN.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Voltronics_JQ.step
  Capacitor_SMD.3dshapes/C_Trimmer_Voltronics_JQ.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Voltronics_JR.step
  Capacitor_SMD.3dshapes/C_Trimmer_Voltronics_JR.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Voltronics_JV.step
  Capacitor_SMD.3dshapes/C_Trimmer_Voltronics_JV.wrl
  Capacitor_SMD.3dshapes/C_Trimmer_Voltronics_JZ.step
  Capacitor_SMD.3dshapes/C_Trimmer_Voltronics_JZ.wrl
Labels: Addition, Pending reviewer

#494 Added 18 missing unmarked non polarized bulk THT capacitors, C_Radial_D....
  Capacitor_THT.3dshapes/C_Radial_D10.0mm_H12.5mm_P5.00mm.step
  Capacitor_THT.3dshapes/C_Radial_D10.0mm_H12.5mm_P5.00mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D10.0mm_H16.0mm_P5.00mm.step
  Capacitor_THT.3dshapes/C_Radial_D10.0mm_H16.0mm_P5.00mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D10.0mm_H20.0mm_P5.00mm.step
  Capacitor_THT.3dshapes/C_Radial_D10.0mm_H20.0mm_P5.00mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D12.5mm_H20.0mm_P5.00mm.step
  Capacitor_THT.3dshapes/C_Radial_D12.5mm_H20.0mm_P5.00mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D12.5mm_H25.0mm_P5.00mm.step
  Capacitor_THT.3dshapes/C_Radial_D12.5mm_H25.0mm_P5.00mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D16.0mm_H25.0mm_P7.50mm.step
  Capacitor_THT.3dshapes/C_Radial_D16.0mm_H25.0mm_P7.50mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D16.0mm_H31.5mm_P7.50mm.step
  Capacitor_THT.3dshapes/C_Radial_D16.0mm_H31.5mm_P7.50mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D18.0mm_H35.5mm_P7.50mm.step
  Capacitor_THT.3dshapes/C_Radial_D18.0mm_H35.5mm_P7.50mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D4.0mm_H5.0mm_P1.50mm.step
  Capacitor_THT.3dshapes/C_Radial_D4.0mm_H5.0mm_P1.50mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D4.0mm_H7.0mm_P1.50mm.step
  Capacitor_THT.3dshapes/C_Radial_D4.0mm_H7.0mm_P1.50mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D5.0mm_H11.0mm_P2.00mm.step
  Capacitor_THT.3dshapes/C_Radial_D5.0mm_H11.0mm_P2.00mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D5.0mm_H5.0mm_P2.00mm.step
  Capacitor_THT.3dshapes/C_Radial_D5.0mm_H5.0mm_P2.00mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D5.0mm_H7.0mm_P2.00mm.step
  Capacitor_THT.3dshapes/C_Radial_D5.0mm_H7.0mm_P2.00mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D6.3mm_H11.0mm_P2.50mm.step
  Capacitor_THT.3dshapes/C_Radial_D6.3mm_H11.0mm_P2.50mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D6.3mm_H5.0mm_P2.50mm.step
  Capacitor_THT.3dshapes/C_Radial_D6.3mm_H5.0mm_P2.50mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D6.3mm_H7.0mm_P2.50mm.step
  Capacitor_THT.3dshapes/C_Radial_D6.3mm_H7.0mm_P2.50mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D8.0mm_H11.5mm_P3.50mm.step
  Capacitor_THT.3dshapes/C_Radial_D8.0mm_H11.5mm_P3.50mm.wrl
  Capacitor_THT.3dshapes/C_Radial_D8.0mm_H7.0mm_P3.50mm.step
  Capacitor_THT.3dshapes/C_Radial_D8.0mm_H7.0mm_P3.50mm.wrl
Labels: Addition, Pending reviewer

#323 Added 3D shape for LEM_LTSR-NP
  Sensor_Current.3dshapes/LEM_LTSR-NP.step
  Sensor_Current.3dshapes/LEM_LTSR-NP.wrl
Labels: Addition, In review

#430 Create LairdTech_28C0236-0JW-10.wrl
  Ferrite_THT.3dshapes/LairdTech_28C0236-0JW-10.step
  Ferrite_THT.3dshapes/LairdTech_28C0236-0JW-10.wrl
Labels: Addition, Pending reviewer

#367 Wemosd1
  Module.3dshapes/src/wemos_d1_mini_light/readme.md
  Module.3dshapes/src/wemos_d1_mini_light/wemos_d1_mini_light.png
  Module.3dshapes/src/wemos_d1_mini_light/wemos_d1_mini_light.py
  Module.3dshapes/src/wemos_d1_mini_light/wemos_d1_mini_light.step
  Module.3dshapes/wemos_d1_mini_light.step
  Module.3dshapes/wemos_d1_mini_light.wrl
Labels: Addition, Pending footprint, Pending reviewer

#516 TO-SOT SMD: Add 3D models for On Semiconductor ECH8 package
  Package_TO_SOT_SMD.3dshapes/OnSemi_ECH8.step
  Package_TO_SOT_SMD.3dshapes/OnSemi_ECH8.wrl
Labels: Addition, Pending reviewer

#522 Removed source to fix issue #521
  Module.3dshapes/src/wemos_d1_mini_light/readme.md
  Module.3dshapes/src/wemos_d1_mini_light/wemos_d1_mini_light.png
  Module.3dshapes/src/wemos_d1_mini_light/wemos_d1_mini_light.py
  Module.3dshapes/src/wemos_d1_mini_light/wemos_d1_mini_light.step
Labels: Bug

#510 Bourns Potentiometer series 3266 and 3296
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3266P_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3266P_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3266W_Vertical.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3266W_Vertical.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3266X_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3266X_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3266Y_Vertical.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3266Y_Vertical.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3266Z_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3266Z_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3296P_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3296P_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3296W_Vertical.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3296W_Vertical.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3296X_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3296X_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3296Y_Vertical.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3296Y_Vertical.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3296Z_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3296Z_Horizontal.wrl
Labels: Addition, Pending reviewer

#486 Added the 3D model for Seiko MS621F
  Battery.3dshapes/BatteryHolder_Seiko_MS621F.step
  Battery.3dshapes/BatteryHolder_Seiko_MS621F.wrl
Labels: Addition, Pending reviewer
