Repository KiCad/kicad-packages3D, pull requests merged in 2019-02, with the labels that each got.

#515 Sensor Pressure: move MPL115A1
  Sensor_Pressure.3dshapes/CREDITS.md
  Sensor_Pressure.3dshapes/NXP_MPL115A1_LGA-8_3x5mm_P1.25mm.step
  Sensor_Pressure.3dshapes/NXP_MPL115A1_LGA-8_3x5mm_P1.25mm.wrl
Labels: Bug, Question

#493 Adding missing tantalum SMD capacitors
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-1608-08_AVX-J.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-1608-08_AVX-J.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-1608-10_AVX-L.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-1608-10_AVX-L.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-2012-15_AVX-P.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-2012-15_AVX-P.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-3216-10_Kemet-I.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-3216-10_Kemet-I.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-3528-15_AVX-H.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-3528-15_AVX-H.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-6032-20_AVX-F.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-6032-20_AVX-F.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7343-15_Kemet-W.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7343-15_Kemet-W.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7343-30_AVX-N.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7343-30_AVX-N.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7343-40_Kemet-Y.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7343-40_Kemet-Y.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7360-38_Kemet-E.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7360-38_Kemet-E.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7361-38_AVX-V.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7361-38_AVX-V.wrl
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7361-438_AVX-U.step
  Capacitor_Tantalum_SMD.3dshapes/CP_EIA-7361-438_AVX-U.wrl
Labels: Addition, Pending reviewer

#440 DCDC XP_Power IA IH ITX ITQ series
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IA48xxD_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IA48xxD_THT.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IA48xxS_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IA48xxS_THT.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IAxxxxD_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IAxxxxD_THT.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IAxxxxS_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IAxxxxS_THT.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IHxxxxDH_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IHxxxxDH_THT.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IHxxxxD_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IHxxxxD_THT.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IHxxxxSH_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IHxxxxSH_THT.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IHxxxxS_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-IHxxxxS_THT.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-ITQxxxxS-H_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-ITQxxxxS-H_THT.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-ITXxxxxSA_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-ITXxxxxSA_THT.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-ITxxxxxS_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_XP_POWER-ITxxxxxS_THT.wrl
Labels: Addition

#526 Add QFN-64-1EP_8x8mm_P0.4mm_EP6.5x6.5mm
  Package_DFN_QFN.3dshapes/QFN-64-1EP_8x8mm_P0.4mm_EP6.5x6.5mm.step
  Package_DFN_QFN.3dshapes/QFN-64-1EP_8x8mm_P0.4mm_EP6.5x6.5mm.wrl
Labels: Addition, Pending reviewer

#530 Add 10 pin DFN, 4x4mm, 0.65mm pitch, with 2.65x3.05mm exposed pad mod…
  Package_DFN_QFN.3dshapes/DFN-10-1EP_4x4mm_P0.65mm_EP2.65x3.05mm.step
  Package_DFN_QFN.3dshapes/DFN-10-1EP_4x4mm_P0.65mm_EP2.65x3.05mm.wrl
Labels: Addition, Pending reviewer
