Repository KiCad/kicad-packages3D, pull requests merged in 2019-06, with the labels that each got.

#533 add Abracon ASV SMD oscillator
  Oscillator.3dshapes/Oscillator_SMD_Abracon_ASV-4Pin_7.0x5.1mm.step
  Oscillator.3dshapes/Oscillator_SMD_Abracon_ASV-4Pin_7.0x5.1mm.wrl
Labels: Addition, Pending reviewer

#509 Added script generated 3D models of the filters
  Filter.3dshapes/Filter_1109-5_1.1x0.9mm.step
  Filter.3dshapes/Filter_1109-5_1.1x0.9mm.wrl
  Filter.3dshapes/Filter_1411-5_1.4x1.1mm.step
  Filter.3dshapes/Filter_1411-5_1.4x1.1mm.wrl
  Filter.3dshapes/Filter_Mini-Circuits_FV1206-1.step
  Filter.3dshapes/Filter_Mini-Circuits_FV1206-1.wrl
  Filter.3dshapes/Filter_Mini-Circuits_FV1206-4.step
  Filter.3dshapes/Filter_Mini-Circuits_FV1206-4.wrl
  Filter.3dshapes/Filter_Mini-Circuits_FV1206-5.step
  Filter.3dshapes/Filter_Mini-Circuits_FV1206-5.wrl
  Filter.3dshapes/Filter_Mini-Circuits_FV1206-6.step
  Filter.3dshapes/Filter_Mini-Circuits_FV1206-6.wrl
  Filter.3dshapes/Filter_Mini-Circuits_FV1206-7.step
  Filter.3dshapes/Filter_Mini-Circuits_FV1206-7.wrl
  Filter.3dshapes/Filter_Mini-Circuits_FV1206.step
  Filter.3dshapes/Filter_Mini-Circuits_FV1206.wrl
Labels: Addition

#569 Package_SO: Add SOIC8 model
  Package_SO.3dshapes/SOIC-8_5.275x5.275mm_P1.27mm.step
  Package_SO.3dshapes/SOIC-8_5.275x5.275mm_P1.27mm.wrl
Labels: Addition, Pending reviewer

#572 Relay_THT: Add Panasonic ADW11 form A model
  Relay_THT.3dshapes/Relay_1P1T_Panasonic_ADW11_FormA.step
  Relay_THT.3dshapes/Relay_1P1T_Panasonic_ADW11_FormA.wrl
Labels: Addition, Pending footprint, Pending reviewer

#575 Revert "Relay_THT: Add Panasonic ADW11 form A model"
  Relay_THT.3dshapes/Relay_1P1T_Panasonic_ADW11_FormA.step
  Relay_THT.3dshapes/Relay_1P1T_Panasonic_ADW11_FormA.wrl
Labels: Bug

#561 Add crystal smd MicroCrystal_MS1V-T1K package
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_MS1V-T1K.step
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_MS1V-T1K.wrl
Labels: Addition, Pending reviewer

#555 Heatsink stonecold hs 132 32x14mm 2x fixation1.5mm
  Heatsink.3dshapes/Heatsink_Stonecold_HS-132_32x14mm_2xFixation1.5mm.step
  Heatsink.3dshapes/Heatsink_Stonecold_HS-132_32x14mm_2xFixation1.5mm.wrl
Labels: Addition, Pending reviewer

#554 I added plcc4 rgb led like very popular ws2812B
  LED_SMD.3dshapes/LED_PLCC4_5.0x5.0mm_P3.2mm.step
  LED_SMD.3dshapes/LED_PLCC4_5.0x5.0mm_P3.2mm.wrl
Labels: Addition, Pending reviewer
