Repository KiCad/kicad-packages3D, pull requests merged in 2020-03, with the labels that each got.

#644 Made the pins a little thicker, 62-pol dsub connecters
  Connector_Dsub.3dshapes/DSUB-62-HD_Female_Horizontal_P2.41x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.step
  Connector_Dsub.3dshapes/DSUB-62-HD_Female_Horizontal_P2.41x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.wrl
  Connector_Dsub.3dshapes/DSUB-62-HD_Female_Horizontal_P2.41x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.step
  Connector_Dsub.3dshapes/DSUB-62-HD_Female_Horizontal_P2.41x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.wrl
  Connector_Dsub.3dshapes/DSUB-62-HD_Female_Horizontal_P2.41x1.98mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-62-HD_Female_Horizontal_P2.41x1.98mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-62-HD_Female_Horizontal_P2.41x2.54mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-62-HD_Female_Horizontal_P2.41x2.54mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-62-HD_Female_Vertical_P2.41x1.98mm_MountingHoles.step
  Connector_Dsub.3dshapes/DSUB-62-HD_Female_Vertical_P2.41x1.98mm_MountingHoles.wrl
  Connector_Dsub.3dshapes/DSUB-62-HD_Male_Horizontal_P2.41x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.step
  Connector_Dsub.3dshapes/DSUB-62-HD_Male_Horizontal_P2.41x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.wrl
  Connector_Dsub.3dshapes/DSUB-62-HD_Male_Horizontal_P2.41x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.step
  Connector_Dsub.3dshapes/DSUB-62-HD_Male_Horizontal_P2.41x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.wrl
  Connector_Dsub.3dshapes/DSUB-62-HD_Male_Horizontal_P2.41x1.98mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-62-HD_Male_Horizontal_P2.41x1.98mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-62-HD_Male_Horizontal_P2.41x2.54mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-62-HD_Male_Horizontal_P2.41x2.54mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-62-HD_Male_Vertical_P2.41x1.98mm_MountingHoles.step
  Connector_Dsub.3dshapes/DSUB-62-HD_Male_Vertical_P2.41x1.98mm_MountingHoles.wrl
Labels: Enhancement, Pending reviewer

#643 Made the pins a little thicker, 44-pol dsub connecters
  Connector_Dsub.3dshapes/DSUB-44-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.step
  Connector_Dsub.3dshapes/DSUB-44-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.wrl
  Connector_Dsub.3dshapes/DSUB-44-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.step
  Connector_Dsub.3dshapes/DSUB-44-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.wrl
  Connector_Dsub.3dshapes/DSUB-44-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-44-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-44-HD_Female_Horizontal_P2.29x2.54mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-44-HD_Female_Horizontal_P2.29x2.54mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-44-HD_Female_Vertical_P2.29x1.98mm_MountingHoles.step
  Connector_Dsub.3dshapes/DSUB-44-HD_Female_Vertical_P2.29x1.98mm_MountingHoles.wrl
  Connector_Dsub.3dshapes/DSUB-44-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.step
  Connector_Dsub.3dshapes/DSUB-44-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.wrl
  Connector_Dsub.3dshapes/DSUB-44-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.step
  Connector_Dsub.3dshapes/DSUB-44-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.wrl
  Connector_Dsub.3dshapes/DSUB-44-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-44-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-44-HD_Male_Horizontal_P2.29x2.54mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-44-HD_Male_Horizontal_P2.29x2.54mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-44-HD_Male_Vertical_P2.29x1.98mm_MountingHoles.step
  Connector_Dsub.3dshapes/DSUB-44-HD_Male_Vertical_P2.29x1.98mm_MountingHoles.wrl
Labels: Enhancement, Pending reviewer

#642 Made the pins a little thicker, 37-pol dsub connecters
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.54mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.54mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset15.98mm.step
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset15.98mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset8.20mm.step
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset8.20mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.step
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset7.70mm_Housed_MountingHolesOffset9.12mm.step
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset7.70mm_Housed_MountingHolesOffset9.12mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset9.90mm_Housed_MountingHolesOffset11.32mm.step
  Connector_Dsub.3dshapes/DSUB-37_Female_Horizontal_P2.77x2.84mm_EdgePinOffset9.90mm_Housed_MountingHolesOffset11.32mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Female_Vertical_P2.77x2.84mm.step
  Connector_Dsub.3dshapes/DSUB-37_Female_Vertical_P2.77x2.84mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Female_Vertical_P2.77x2.84mm_MountingHoles.step
  Connector_Dsub.3dshapes/DSUB-37_Female_Vertical_P2.77x2.84mm_MountingHoles.wrl
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.54mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.54mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset15.98mm.step
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset15.98mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset8.20mm.step
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset8.20mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.step
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset7.70mm_Housed_MountingHolesOffset9.12mm.step
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset7.70mm_Housed_MountingHolesOffset9.12mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset9.90mm_Housed_MountingHolesOffset11.32mm.step
  Connector_Dsub.3dshapes/DSUB-37_Male_Horizontal_P2.77x2.84mm_EdgePinOffset9.90mm_Housed_MountingHolesOffset11.32mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Male_Vertical_P2.77x2.84mm.step
  Connector_Dsub.3dshapes/DSUB-37_Male_Vertical_P2.77x2.84mm.wrl
  Connector_Dsub.3dshapes/DSUB-37_Male_Vertical_P2.77x2.84mm_MountingHoles.step
  Connector_Dsub.3dshapes/DSUB-37_Male_Vertical_P2.77x2.84mm_MountingHoles.wrl
Labels: Enhancement, Pending reviewer

#641 Made the pins a little thicker
  Connector_Dsub.3dshapes/DSUB-26-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.step
  Connector_Dsub.3dshapes/DSUB-26-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.wrl
  Connector_Dsub.3dshapes/DSUB-26-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.step
  Connector_Dsub.3dshapes/DSUB-26-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.wrl
  Connector_Dsub.3dshapes/DSUB-26-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-26-HD_Female_Horizontal_P2.29x1.98mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-26-HD_Female_Horizontal_P2.29x2.54mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-26-HD_Female_Horizontal_P2.29x2.54mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-26-HD_Female_Vertical_P2.29x1.98mm_MountingHoles.step
  Connector_Dsub.3dshapes/DSUB-26-HD_Female_Vertical_P2.29x1.98mm_MountingHoles.wrl
  Connector_Dsub.3dshapes/DSUB-26-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.step
  Connector_Dsub.3dshapes/DSUB-26-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset3.03mm_Housed_MountingHolesOffset4.94mm.wrl
  Connector_Dsub.3dshapes/DSUB-26-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.step
  Connector_Dsub.3dshapes/DSUB-26-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset8.35mm_Housed_MountingHolesOffset10.89mm.wrl
  Connector_Dsub.3dshapes/DSUB-26-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-26-HD_Male_Horizontal_P2.29x1.98mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-26-HD_Male_Horizontal_P2.29x2.54mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-26-HD_Male_Horizontal_P2.29x2.54mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-26-HD_Male_Vertical_P2.29x1.98mm_MountingHoles.step
  Connector_Dsub.3dshapes/DSUB-26-HD_Male_Vertical_P2.29x1.98mm_MountingHoles.wrl
Labels: Enhancement, Pending reviewer

#640 Made the pins a little thicker
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.54mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.54mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset15.98mm.step
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset15.98mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset8.20mm.step
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset8.20mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.step
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset7.70mm_Housed_MountingHolesOffset9.12mm.step
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset7.70mm_Housed_MountingHolesOffset9.12mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset9.90mm_Housed_MountingHolesOffset11.32mm.step
  Connector_Dsub.3dshapes/DSUB-25_Female_Horizontal_P2.77x2.84mm_EdgePinOffset9.90mm_Housed_MountingHolesOffset11.32mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Female_Vertical_P2.77x2.84mm.step
  Connector_Dsub.3dshapes/DSUB-25_Female_Vertical_P2.77x2.84mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Female_Vertical_P2.77x2.84mm_MountingHoles.step
  Connector_Dsub.3dshapes/DSUB-25_Female_Vertical_P2.77x2.84mm_MountingHoles.wrl
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.54mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.54mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset15.98mm.step
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset15.98mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset8.20mm.step
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset14.56mm_Housed_MountingHolesOffset8.20mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.step
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset7.70mm_Housed_MountingHolesOffset9.12mm.step
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset7.70mm_Housed_MountingHolesOffset9.12mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset9.40mm.step
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset9.40mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset9.90mm_Housed_MountingHolesOffset11.32mm.step
  Connector_Dsub.3dshapes/DSUB-25_Male_Horizontal_P2.77x2.84mm_EdgePinOffset9.90mm_Housed_MountingHolesOffset11.32mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Male_Vertical_P2.77x2.84mm.step
  Connector_Dsub.3dshapes/DSUB-25_Male_Vertical_P2.77x2.84mm.wrl
  Connector_Dsub.3dshapes/DSUB-25_Male_Vertical_P2.77x2.84mm_MountingHoles.step
  Connector_Dsub.3dshapes/DSUB-25_Male_Vertical_P2.77x2.84mm_MountingHoles.wrl
Labels: Enhancement, Pending reviewer

#517 Add ESP-12E
  RF_Module.3dshapes/ESP-12E.step
  RF_Module.3dshapes/ESP-12E.wrl
Labels: Addition, Pending reviewer

#573 Added 3D model TDFN-6-1EP_2.5x2.5mm_P0.65mm_EP1.3x2mm
  Package_DFN_QFN.3dshapes/TDFN-6-1EP_2.5x2.5mm_P0.65mm_EP1.3x2mm.step
  Package_DFN_QFN.3dshapes/TDFN-6-1EP_2.5x2.5mm_P0.65mm_EP1.3x2mm.wrl
Labels: Addition, Pending reviewer

#589 Scripted 3D models of resonator C26 and C38
  Crystal.3dshapes/Crystal_C26-LF_D2.1mm_L6.5mm_Horizontal.step
  Crystal.3dshapes/Crystal_C26-LF_D2.1mm_L6.5mm_Horizontal.wrl
  Crystal.3dshapes/Crystal_C26-LF_D2.1mm_L6.5mm_Horizontal_1EP_style1.step
  Crystal.3dshapes/Crystal_C26-LF_D2.1mm_L6.5mm_Horizontal_1EP_style1.wrl
  Crystal.3dshapes/Crystal_C26-LF_D2.1mm_L6.5mm_Horizontal_1EP_style2.step
  Crystal.3dshapes/Crystal_C26-LF_D2.1mm_L6.5mm_Horizontal_1EP_style2.wrl
  Crystal.3dshapes/Crystal_C26-LF_D2.1mm_L6.5mm_Vertical.step
  Crystal.3dshapes/Crystal_C26-LF_D2.1mm_L6.5mm_Vertical.wrl
  Crystal.3dshapes/Crystal_C38-LF_D3.0mm_L8.0mm_Horizontal.step
  Crystal.3dshapes/Crystal_C38-LF_D3.0mm_L8.0mm_Horizontal.wrl
  Crystal.3dshapes/Crystal_C38-LF_D3.0mm_L8.0mm_Horizontal_1EP_style1.step
  Crystal.3dshapes/Crystal_C38-LF_D3.0mm_L8.0mm_Horizontal_1EP_style1.wrl
  Crystal.3dshapes/Crystal_C38-LF_D3.0mm_L8.0mm_Horizontal_1EP_style2.step
  Crystal.3dshapes/Crystal_C38-LF_D3.0mm_L8.0mm_Horizontal_1EP_style2.wrl
  Crystal.3dshapes/Crystal_C38-LF_D3.0mm_L8.0mm_Vertical.step
  Crystal.3dshapes/Crystal_C38-LF_D3.0mm_L8.0mm_Vertical.wrl
Labels: Addition, Pending reviewer

#571 Added Phoenix terminal block serie MKDS, 5.08mm Horizontal
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-10-5.08_1x10_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-10-5.08_1x10_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-11-5.08_1x11_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-11-5.08_1x11_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-12-5.08_1x12_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-12-5.08_1x12_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-13-5.08_1x13_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-13-5.08_1x13_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-14-5.08_1x14_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-14-5.08_1x14_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-15-5.08_1x15_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-15-5.08_1x15_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-16-5.08_1x16_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-16-5.08_1x16_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-2-5.08_1x02_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-2-5.08_1x02_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-3-5.08_1x03_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-3-5.08_1x03_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-4-5.08_1x04_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-4-5.08_1x04_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-5-5.08_1x05_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-5-5.08_1x05_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-6-5.08_1x06_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-6-5.08_1x06_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-7-5.08_1x07_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-7-5.08_1x07_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-8-5.08_1x08_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-8-5.08_1x08_P5.08mm_Horizontal.wrl
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-9-5.08_1x09_P5.08mm_Horizontal.step
  TerminalBlock_Phoenix.3dshapes/TerminalBlock_Phoenix_MKDS-1,5-9-5.08_1x09_P5.08mm_Horizontal.wrl
Labels: Addition, Pending reviewer

#629 Added QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.
  Package_DFN_QFN.3dshapes/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.step
  Package_DFN_QFN.3dshapes/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.wrl
Labels: Addition

#585 Added scripts for murata resonator chip
  Crystal.3dshapes/Resonator_SMD-3Pin_7.2x3.0mm.step
  Crystal.3dshapes/Resonator_SMD-3Pin_7.2x3.0mm.wrl
  Crystal.3dshapes/Resonator_SMD_muRata_CDSCB-2Pin_4.5x2.0mm.step
  Crystal.3dshapes/Resonator_SMD_muRata_CDSCB-2Pin_4.5x2.0mm.wrl
  Crystal.3dshapes/Resonator_SMD_muRata_CSTxExxV-3Pin_3.0x1.1mm.step
  Crystal.3dshapes/Resonator_SMD_muRata_CSTxExxV-3Pin_3.0x1.1mm.wrl
  Crystal.3dshapes/Resonator_SMD_muRata_SFECV-3Pin_6.9x2.9mm.step
  Crystal.3dshapes/Resonator_SMD_muRata_SFECV-3Pin_6.9x2.9mm.wrl
  Crystal.3dshapes/Resonator_SMD_muRata_SFSKA-3Pin_7.9x3.8mm.step
  Crystal.3dshapes/Resonator_SMD_muRata_SFSKA-3Pin_7.9x3.8mm.wrl
  Crystal.3dshapes/Resonator_SMD_muRata_TPSKA-3Pin_7.9x3.8mm.step
  Crystal.3dshapes/Resonator_SMD_muRata_TPSKA-3Pin_7.9x3.8mm.wrl
Labels: Addition, Pending reviewer

#591 Added 3D models of micro crystals smd series of crystals
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CC1V-T1A-2Pin_8.0x3.7mm.step
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CC1V-T1A-2Pin_8.0x3.7mm.wrl
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CC4V-T1A-2Pin_5.0x1.9mm.step
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CC4V-T1A-2Pin_5.0x1.9mm.wrl
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CC5V-T1A-2Pin_4.1x1.5mm.step
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CC5V-T1A-2Pin_4.1x1.5mm.wrl
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CC7V-T1A-2Pin_3.2x1.5mm.step
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CC7V-T1A-2Pin_3.2x1.5mm.wrl
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CC8V-T1A-2Pin_2.0x1.2mm.step
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CC8V-T1A-2Pin_2.0x1.2mm.wrl
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CM9V-T1A-2Pin_1.6x1.0mm.step
  Crystal.3dshapes/Crystal_SMD_MicroCrystal_CM9V-T1A-2Pin_1.6x1.0mm.wrl
Labels: Addition, Pending reviewer

#564 3D models for SANYOU_SRD_Series
  Relay_THT.3dshapes/Relay_SPDT_SANYOU_SRD_Series_Form_C.step
  Relay_THT.3dshapes/Relay_SPDT_SANYOU_SRD_Series_Form_C.wrl
  Relay_THT.3dshapes/Relay_SPST_SANYOU_SRD_Series_Form_A.step
  Relay_THT.3dshapes/Relay_SPST_SANYOU_SRD_Series_Form_A.wrl
  Relay_THT.3dshapes/Relay_SPST_SANYOU_SRD_Series_Form_B.step
  Relay_THT.3dshapes/Relay_SPST_SANYOU_SRD_Series_Form_B.wrl
Labels: Addition, Pending reviewer, Re-push

#647 Added 3D for Omron B3FS-105xP.
  Button_Switch_SMD.3dshapes/SW_SPST_Omron_B3FS-105xP.step
  Button_Switch_SMD.3dshapes/SW_SPST_Omron_B3FS-105xP.wrl
Labels: Addition, Pending reviewer

#590 Added 3D models for crystal 0603 2 and 4 pin
  Crystal.3dshapes/Crystal_SMD_0603-2Pin_6.0x3.5mm.step
  Crystal.3dshapes/Crystal_SMD_0603-2Pin_6.0x3.5mm.wrl
  Crystal.3dshapes/Crystal_SMD_0603-4Pin_6.0x3.5mm.step
  Crystal.3dshapes/Crystal_SMD_0603-4Pin_6.0x3.5mm.wrl
Labels: Addition, Pending reviewer

#582 Added scripted 3D model for LED_RGB_1210
  LED_SMD.3dshapes/LED_RGB_1210.step
  LED_SMD.3dshapes/LED_RGB_1210.wrl
Labels: Addition, Pending reviewer

#586 Added AT310 3D models
  Crystal.3dshapes/Crystal_AT310_D3.0mm_L10.0mm_Horizontal.step
  Crystal.3dshapes/Crystal_AT310_D3.0mm_L10.0mm_Horizontal.wrl
  Crystal.3dshapes/Crystal_AT310_D3.0mm_L10.0mm_Horizontal_1EP_style1.step
  Crystal.3dshapes/Crystal_AT310_D3.0mm_L10.0mm_Horizontal_1EP_style1.wrl
  Crystal.3dshapes/Crystal_AT310_D3.0mm_L10.0mm_Horizontal_1EP_style2.step
  Crystal.3dshapes/Crystal_AT310_D3.0mm_L10.0mm_Horizontal_1EP_style2.wrl
  Crystal.3dshapes/Crystal_AT310_D3.0mm_L10.0mm_Vertical.step
  Crystal.3dshapes/Crystal_AT310_D3.0mm_L10.0mm_Vertical.wrl
Labels: Addition, Pending reviewer

#484 Added a number of 3D models for sip components
  Package_SIP.3dshapes/PowerIntegrations_eSIP-7C.step
  Package_SIP.3dshapes/PowerIntegrations_eSIP-7C.wrl
  Package_SIP.3dshapes/PowerIntegrations_eSIP-7F.step
  Package_SIP.3dshapes/PowerIntegrations_eSIP-7F.wrl
  Package_SIP.3dshapes/SIP-8_19x3mm_P2.54mm.step
  Package_SIP.3dshapes/SIP-8_19x3mm_P2.54mm.wrl
  Package_SIP.3dshapes/SIP-9_21.54x3mm_P2.54mm.step
  Package_SIP.3dshapes/SIP-9_21.54x3mm_P2.54mm.wrl
  Package_SIP.3dshapes/SIP4_Sharp-SSR_P7.62mm_Angled.step
  Package_SIP.3dshapes/SIP4_Sharp-SSR_P7.62mm_Angled.wrl
  Package_SIP.3dshapes/SIP4_Sharp-SSR_P7.62mm_Straight.step
  Package_SIP.3dshapes/SIP4_Sharp-SSR_P7.62mm_Straight.wrl
  Package_SIP.3dshapes/SLA704XM.step
  Package_SIP.3dshapes/SLA704XM.wrl
  Package_SIP.3dshapes/STK672-040-E.step
  Package_SIP.3dshapes/STK672-040-E.wrl
  Package_SIP.3dshapes/STK672-080-E.step
  Package_SIP.3dshapes/STK672-080-E.wrl
  Package_SIP.3dshapes/Sanyo_STK4xx-15_59.2x8.0mm_P2.54mm.step
  Package_SIP.3dshapes/Sanyo_STK4xx-15_59.2x8.0mm_P2.54mm.wrl
  Package_SIP.3dshapes/Sanyo_STK4xx-15_78.0x8.0mm_P2.54mm.step
  Package_SIP.3dshapes/Sanyo_STK4xx-15_78.0x8.0mm_P2.54mm.wrl
Labels: Addition, Ready for review

#576 Changed the pin length to 2.5 mm
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0005FF_L8.3mm_W3.8mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0005FF_L8.3mm_W3.8mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0008FF_L8.3mm_W3.8mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0008FF_L8.3mm_W3.8mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0012FF_L8.3mm_W3.8mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0012FF_L8.3mm_W3.8mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0016FF_L9.9mm_W3.8mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0016FF_L9.9mm_W3.8mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0025FF_L9.6mm_W3.8mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0025FF_L9.6mm_W3.8mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0033FF_L11.4mm_W3.8mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0033FF_L11.4mm_W3.8mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0040FF_L11.5mm_W3.8mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0040FF_L11.5mm_W3.8mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0055FF_L14.0mm_W4.1mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0055FF_L14.0mm_W4.1mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0075FF_L11.5mm_W4.8mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0075FF_L11.5mm_W4.8mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0100FF_L18.7mm_W5.1mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0100FF_L18.7mm_W5.1mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0125FF_L21.2mm_W5.3mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0125FF_L21.2mm_W5.3mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0150FF_L23.4mm_W5.3mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0150FF_L23.4mm_W5.3mm.wrl
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0200FF_L24.9mm_W6.1mm.step
  Fuse.3dshapes/Fuse_BelFuse_0ZRE_0ZRE0200FF_L24.9mm_W6.1mm.wrl
Labels: Addition
