Repository KiCad/kicad-packages3D, pull requests merged in 2020-02, with the labels that each got.

#598 Added 3D models of Bournes serie 3299P 3299W 3299X 3299Y 3299Z
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3299P_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3299P_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3299W_Vertical.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3299W_Vertical.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3299X_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3299X_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3299Y_Vertical.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3299Y_Vertical.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3299Z_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3299Z_Horizontal.wrl
Labels: Addition, Pending reviewer

#597 Added 3D models of Bournse potentiometer serie 3005, 3006, 3009
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3005_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3005_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3006P_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3006P_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3006W_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3006W_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3006Y_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3006Y_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3009P_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3009P_Horizontal.wrl
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3009Y_Horizontal.step
  Potentiometer_THT.3dshapes/Potentiometer_Bourns_3009Y_Horizontal.wrl
Labels: Addition

#645 9-pol dsub, moved anchor 1 mm for model Horizontal_P2.77x2.84mm_EdgePinOffset4.94…
  Connector_Dsub.3dshapes/DSUB-9_Female_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.step
  Connector_Dsub.3dshapes/DSUB-9_Female_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.wrl
  Connector_Dsub.3dshapes/DSUB-9_Male_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.step
  Connector_Dsub.3dshapes/DSUB-9_Male_Horizontal_P2.77x2.84mm_EdgePinOffset4.94mm_Housed_MountingHolesOffset7.48mm.wrl
Labels: Bug

#624 Added 3D for VL53L1x.
  Sensor_Distance.3dshapes/ST_VL53L1x.step
  Sensor_Distance.3dshapes/ST_VL53L1x.wrl
Labels: Addition, Pending footprint, Pending reviewer
