Repository KiCad/kicad-packages3D, pull requests merged in 2020-08, with the labels that each got.

#710 Added D_DO-247-2_Vertical 3D
  Diode_THT.3dshapes/D_DO-247_Vertical.step
  Diode_THT.3dshapes/D_DO-247_Vertical.wrl
Labels: Addition

#709 Added IXYS_GUFP 3D
  Diode_THT.3dshapes/Diode_Bridge_IXYS_GUFP.step
  Diode_THT.3dshapes/Diode_Bridge_IXYS_GUFP.wrl
Labels: Addition, Pending changes

#625 Added DFN-8-1EP_2x2mm_P0.5mm_EP0.7x1.3mm.
  Package_DFN_QFN.3dshapes/DFN-8-1EP_2x2mm_P0.5mm_EP0.7x1.3mm.step
  Package_DFN_QFN.3dshapes/DFN-8-1EP_2x2mm_P0.5mm_EP0.7x1.3mm.wrl
Labels: Addition

#603 Add 3d models for XT60 male and female connectors.
  Connector_AMASS.3dshapes/AMASS_XT60-F_1x02_P7.2mm_Vertical.step
  Connector_AMASS.3dshapes/AMASS_XT60-F_1x02_P7.2mm_Vertical.wrl
  Connector_AMASS.3dshapes/AMASS_XT60-M_1x02_P7.2mm_Vertical.step
  Connector_AMASS.3dshapes/AMASS_XT60-M_1x02_P7.2mm_Vertical.wrl
Labels: Addition

#667 Added Omron G2RL THT relay.
  Relay_THT.3dshapes/Relay_DPDT_Omron_G2RL.step
  Relay_THT.3dshapes/Relay_DPDT_Omron_G2RL.wrl
Labels: Addition

#672 Added 3D for SMD fuses
  Fuse.3dshapes/Fuse_0402_1005Metric.step
  Fuse.3dshapes/Fuse_0402_1005Metric.wrl
  Fuse.3dshapes/Fuse_0603_1608Metric.step
  Fuse.3dshapes/Fuse_0603_1608Metric.wrl
  Fuse.3dshapes/Fuse_0805_2012Metric.step
  Fuse.3dshapes/Fuse_0805_2012Metric.wrl
  Fuse.3dshapes/Fuse_1206_3216Metric.step
  Fuse.3dshapes/Fuse_1206_3216Metric.wrl
  Fuse.3dshapes/Fuse_1210_3225Metric.step
  Fuse.3dshapes/Fuse_1210_3225Metric.wrl
Labels: Addition

#717 Add L_1008_2520Metric
  Inductor_SMD.3dshapes/L_1008_2520Metric.step
  Inductor_SMD.3dshapes/L_1008_2520Metric.wrl
Labels: Addition

#665 Created model for 5mm LED Staggred Pins
  LED_THT.3dshapes/LED_D5.0mm-4_RGB_Staggered_Pins.step
  LED_THT.3dshapes/LED_D5.0mm-4_RGB_Staggered_Pins.wrl
Labels: Addition

#692 Add TQFN-20-1EP_5x5mm_P0.65mm_EP3.1x3.1mm
  Package_DFN_QFN.3dshapes/TQFN-20-1EP_5x5mm_P0.65mm_EP3.1x3.1mm.step
  Package_DFN_QFN.3dshapes/TQFN-20-1EP_5x5mm_P0.65mm_EP3.1x3.1mm.wrl
Labels: Addition, Pending reviewer
