Repository KiCad/kicad-packages3D, pull requests merged in 2020-01, with the labels that each got.

#581 Added 3D model LED_RGB_5050-6
  LED_SMD.3dshapes/LED_RGB_5050-6.step
  LED_SMD.3dshapes/LED_RGB_5050-6.wrl
Labels: Enhancement, Pending changes

#650 Add SOP-4_4.4x2.6mm_P1.27mm, rm SOP-4_4.4x2.8mm
  Package_SO.3dshapes/SOP-4_4.4x2.6mm_P1.27mm.step
  Package_SO.3dshapes/SOP-4_4.4x2.6mm_P1.27mm.wrl
  Package_SO.3dshapes/SOP-4_4.4x2.8mm_P1.27mm.step
  Package_SO.3dshapes/SOP-4_4.4x2.8mm_P1.27mm.wrl
Labels: Bug

#617 Varistor: Add missing models
  Varistor.3dshapes/RV_Disc_D16.5mm_W6.7mm_P7.5mm.step
  Varistor.3dshapes/RV_Disc_D16.5mm_W6.7mm_P7.5mm.wrl
  Varistor.3dshapes/RV_Disc_D9mm_W6.1mm_P5mm.step
  Varistor.3dshapes/RV_Disc_D9mm_W6.1mm_P5mm.wrl
Labels: Addition, Pending reviewer

#626 Added SOD-923.
  Diode_SMD.3dshapes/D_SOD-923.step
  Diode_SMD.3dshapes/D_SOD-923.wrl
Labels: Addition, Pending reviewer

#648 Fixed Keystone 2479 3D
  Battery.3dshapes/BatteryHolder_Keystone_2479_3xAAA.step
  Battery.3dshapes/BatteryHolder_Keystone_2479_3xAAA.wrl
Labels: Enhancement, Pending reviewer

#605 Added 3D models for AST1109MLTRQ
  Buzzer_Beeper.3dshapes/Buzzer_Mallory_AST1109MLTRQ.step
  Buzzer_Beeper.3dshapes/Buzzer_Mallory_AST1109MLTRQ.wrl
Labels: Addition, Pending reviewer
