Repository KiCad/kicad-packages3D, pull requests merged in 2020-09, with the labels that each got.

#720 MountyRox: Battery holder type Eagle 12BH611 added.
  Battery.3dshapes/BatteryHolder_Eagle_12BH611-GR.step
  Battery.3dshapes/BatteryHolder_Eagle_12BH611-GR.wrl
Labels: Addition

#691 Add Buzzer_Beeper/Indicator_PUI_AI-1440-TWT-24V-2-R
  Buzzer_Beeper.3dshapes/Indicator_PUI_AI-1440-TWT-24V-2-R.step
  Buzzer_Beeper.3dshapes/Indicator_PUI_AI-1440-TWT-24V-2-R.wrl
Labels: Addition, Pending changes

#729 Update Murata NXE2
  Converter_DCDC.3dshapes/Converter_DCDC_Murata_NXE2SxxxxMC_SMD.step
  Converter_DCDC.3dshapes/Converter_DCDC_Murata_NXE2SxxxxMC_SMD.wrl
  Converter_DCDC.3dshapes/Converter_DCDC_muRata_NXE2SxxxxMC_THT.step
  Converter_DCDC.3dshapes/Converter_DCDC_muRata_NXE2SxxxxMC_THT.wrl
Labels: Enhancement

#722 Added 3D for balun Johanson 0900PC15J0013
  RF_Converter.3dshapes/Balun_Johanson_0900PC15J0013.step
  RF_Converter.3dshapes/Balun_Johanson_0900PC15J0013.wrl
Labels: Addition

#674 Added 3D for CUI CUI_CMC-4013-SMT SMD microphone
  Sensor_Audio.3dshapes/CUI_CMC-4013-SMT.step
  Sensor_Audio.3dshapes/CUI_CMC-4013-SMT.wrl
Labels: Addition

#699 Add Oscillator_SMD_Fox_FT5H_5.0x3.2mm
  Oscillator.3dshapes/Oscillator_SMD_Fox_FT5H_5.0x3.2mm.step
  Oscillator.3dshapes/Oscillator_SMD_Fox_FT5H_5.0x3.2mm.wrl
Labels: Addition

#733 Added 3d model for the LM399
  Package_TO_SOT_THT.3dshapes/Analog_TO-46-4_ThermalShield.step
  Package_TO_SOT_THT.3dshapes/Analog_TO-46-4_ThermalShield.wrl
Labels: Addition
